[package]
name = "io-pimdir"
description = "Rust implementation of Pimdir standard"
version = "0.3.0"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.87"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["api-bindings", "command-line-utilities", "database", "no-std"]
keywords = ["pimdir", "sqlite", "storage", "no-std", "io-free"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/io-pimdir/latest/io_pimdir"
repository = "https://github.com/pimalaya/io-pimdir"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["client"]
client = ["dep:fs4", "dep:rusqlite"]
cli = ["client", "dep:anyhow", "dep:clap", "dep:humantime", "dep:log", "pimalaya-cli/prompt", "pimalaya-cli/table", "pimalaya-cli/terminal"]

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[[bin]]
name = "pimdir"
path = "src/main.rs"
required-features = ["cli"]

[build-dependencies]
pimalaya-cli = { version = "0.2", default-features = false, features = ["build"], optional = true }

[dev-dependencies]
fs4 = { version = "1.1", default-features = false, features = ["sync"] }
proptest = { version = "1", default-features = false, features = ["std"] }
rusqlite = { version = "0.40", default-features = false, features = ["bundled"] }
tempfile = { version = "3", default-features = false }

[dependencies]
anyhow = { version = "1", default-features = false, features = ["std"], optional = true }
blake3 = { version = "1", default-features = false }
clap = { version = "4.4", features = ["derive", "wrap_help"], optional = true }
fs4 = { version = "1.1", default-features = false, features = ["sync"], optional = true }
humantime = { version = "2.2", optional = true }
io-replica = "0.4"
log = { version = "0.4", default-features = false, optional = true }
pimalaya-cli = { version = "0.2", default-features = false, optional = true }
rusqlite = { version = "0.40", default-features = false, features = ["bundled"], optional = true }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
sha2 = { version = "0.11", default-features = false }

[patch.crates-io]
io-replica.git = "https://github.com/pimalaya/io-replica"
