//! The crate's inlined SQL against the canonical pimdir specification.
//!
//! `sql` exists to be the copy of the spec's SQL, reachable by name so a
//! consumer holding its own SQLite driver can run it without
//! transcribing anything. That promise is only worth something if the
//! copy is checked: the crate and the spec live in separate
//! repositories, so nothing else notices when one moves and the other
//! does not, and the drift stays invisible until a store is created with
//! a column the readers expect and the writer never made.
//!
//! Three things are checked, and deliberately not a fourth. The schema
//! must be semantically identical, migrations being normative, so a
//! missing column, default, foreign-key action or index is a defect;
//! compared through SQLite's own pragmas rather than by text, so
//! formatting is free to differ. Every canonical statement must exist
//! here by name, since an implementation may not silently omit an
//! operation. Every canonical statement must prepare against the
//! canonical schema, this being the only place the spec's own SQL is
//! ever loaded. Statement text is not compared: SPEC §4.4 permits an
//! equivalent substitution preserving the same invariants, and this
//! crate uses one deliberately.
//!
//! The spec is a sibling checkout rather than a vendored copy, so the
//! test skips when it is absent and runs when the two sit side by side.

use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use io_pimdir::sql;
use rusqlite::Connection;

/// The canonical spec checkout, beside this one.
fn spec_dir() -> Option<PathBuf> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()?
        .join("pimdir");

    dir.join("migrations/0001_init.sql")
        .is_file()
        .then_some(dir)
}

/// One column as SQLite reports it: name, declared type, not-null,
/// default and primary-key position.
type Column = (String, String, i64, Option<String>, i64);

/// One foreign key as SQLite reports it: the child column, the parent
/// table and column, and the update and delete actions.
type ForeignKey = (String, String, Option<String>, String, String);

fn tables(conn: &Connection) -> Vec<String> {
    let mut stmt = conn
        .prepare("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name")
        .unwrap();
    let rows = stmt.query_map([], |row| row.get(0)).unwrap();
    rows.map(Result::unwrap).collect()
}

fn columns(conn: &Connection, table: &str) -> Vec<Column> {
    let mut stmt = conn
        .prepare(&format!("SELECT name, type, \"notnull\", dflt_value, pk FROM pragma_table_info('{table}') ORDER BY name"))
        .unwrap();
    let rows = stmt
        .query_map([], |row| {
            Ok((
                row.get(0)?,
                row.get(1)?,
                row.get(2)?,
                row.get(3)?,
                row.get(4)?,
            ))
        })
        .unwrap();
    rows.map(Result::unwrap).collect()
}

fn foreign_keys(conn: &Connection, table: &str) -> BTreeSet<ForeignKey> {
    let mut stmt = conn
        .prepare(&format!(
            "SELECT \"from\", \"table\", \"to\", on_update, on_delete FROM pragma_foreign_key_list('{table}')"
        ))
        .unwrap();
    let rows = stmt
        .query_map([], |row| {
            Ok((
                row.get(0)?,
                row.get(1)?,
                row.get(2)?,
                row.get(3)?,
                row.get(4)?,
            ))
        })
        .unwrap();
    rows.map(Result::unwrap).collect()
}

/// Indexes the schema declares, with their columns and partiality.
/// Excludes the ones SQLite creates for a `UNIQUE` constraint under an
/// autogenerated name, since the compared columns already imply them.
fn indexes(conn: &Connection, table: &str) -> BTreeSet<(String, String, bool)> {
    let mut stmt = conn
        .prepare(&format!(
            "SELECT name, origin, partial FROM pragma_index_list('{table}') WHERE origin = 'c'"
        ))
        .unwrap();
    let names: Vec<(String, bool)> = stmt
        .query_map([], |row| Ok((row.get(0)?, row.get::<_, i64>(2)? == 1)))
        .unwrap()
        .map(Result::unwrap)
        .collect();

    names
        .into_iter()
        .map(|(name, partial)| {
            let mut cols = conn
                .prepare(&format!(
                    "SELECT name FROM pragma_index_info('{name}') ORDER BY seqno"
                ))
                .unwrap();
            let list: Vec<String> = cols
                .query_map([], |row| row.get(0))
                .unwrap()
                .map(Result::unwrap)
                .collect();
            (name, list.join(","), partial)
        })
        .collect()
}

fn applied(ddl: &str) -> Connection {
    let conn = Connection::open_in_memory().unwrap();
    conn.execute_batch(ddl)
        .expect("the schema applies to an empty database");
    conn
}

#[test]
fn the_inlined_schema_matches_the_spec() {
    let Some(spec) = spec_dir() else {
        eprintln!("skipped: no pimdir spec checkout beside this one");
        return;
    };

    let canonical = applied(&fs::read_to_string(spec.join("migrations/0001_init.sql")).unwrap());
    let inlined = applied(sql::MIGRATION_0001);

    assert_eq!(
        tables(&canonical),
        tables(&inlined),
        "the inlined schema declares a different set of tables"
    );

    for table in tables(&canonical) {
        assert_eq!(
            columns(&canonical, &table),
            columns(&inlined, &table),
            "table `{table}`: columns differ (name, type, not-null, default or primary key)"
        );
        assert_eq!(
            foreign_keys(&canonical, &table),
            foreign_keys(&inlined, &table),
            "table `{table}`: foreign keys differ. An `ON UPDATE` mismatch is the \
             quiet one: it does not fail until something is renamed"
        );
        assert_eq!(
            indexes(&canonical, &table),
            indexes(&inlined, &table),
            "table `{table}`: declared indexes differ"
        );
    }
}

#[test]
fn every_canonical_statement_is_inlined() {
    let Some(spec) = spec_dir() else {
        eprintln!("skipped: no pimdir spec checkout beside this one");
        return;
    };

    let canonical: BTreeSet<String> = canonical_statements(&spec)
        .into_iter()
        .map(|(name, _)| name)
        .collect();

    let inlined: BTreeSet<String> = sql::ALL.iter().map(|(name, _)| name.to_string()).collect();
    let missing: Vec<&String> = canonical
        .difference(&inlined)
        .filter(|name| !SUBSTITUTED.contains(&name.as_str()))
        .collect();

    assert!(
        missing.is_empty(),
        "canonical statements with no constant here (and so unreachable by name, \
         which is what `sql::ALL` exists for): {missing:?}. If one is a deliberate \
         §4.4 substitution, add it to SUBSTITUTED with the statement that replaces it"
    );
}

/// Every canonical statement the spec checkout carries, as
/// `(CONSTANT_NAME, sql)`.
///
/// The files are the format's own reference statements, split on the
/// `-- name:` marker each is introduced by.
fn canonical_statements(spec: &Path) -> Vec<(String, String)> {
    let mut statements = Vec::new();

    for file in [
        "items",
        "collections",
        "bindings",
        "sources",
        "objects",
        "queue",
    ] {
        let text = fs::read_to_string(spec.join(format!("queries/{file}.sql"))).unwrap();
        for chunk in text.split("-- name: ").skip(1) {
            let mut lines = chunk.lines();
            let name = lines.next().unwrap().trim().to_uppercase();
            let sql: String = lines
                .filter(|line| !line.trim_start().starts_with("--"))
                .collect::<Vec<_>>()
                .join("\n");
            statements.push((name, sql.trim().to_string()));
        }
    }

    statements
}

/// Every canonical statement prepares against the canonical schema.
///
/// The name check above says the crate reaches each one; this says the
/// format's own SQL is SQL and agrees with the format's own schema.
/// Nothing else checks it: this repository holds the only toolchain that
/// ever loads those files.
#[test]
fn every_canonical_statement_prepares() {
    let Some(spec) = spec_dir() else {
        eprintln!("skipped: no pimdir spec checkout beside this one");
        return;
    };

    let migration = fs::read_to_string(spec.join("migrations/0001_init.sql")).unwrap();
    let conn = applied(&migration);

    for (name, sql) in canonical_statements(&spec) {
        if let Err(err) = conn.prepare(&sql) {
            panic!("canonical `{name}` does not prepare against the canonical schema: {err:?}");
        }
    }
}

/// Canonical statements this crate deliberately does not inline, each replaced
/// by an equivalent that preserves the same invariant (SPEC §4.4, §7).
///
/// The list is short on purpose. Every entry is a place where reading the
/// spec and reading this crate will not line up, so each names what it
/// swapped for; an omission that cannot be justified here is drift.
const SUBSTITUTED: &[&str] = &[
    // belongs to the reference load-all / replace-all save. This crate
    // saves by diff instead, so it never clears a collection to rewrite
    // it: the persisted state is identical, and the diffed form keeps an
    // item's `sort_key` (§9.3) without carrying it back out.
    "DELETE_ITEMS",
];

#[test]
fn every_inlined_statement_prepares() {
    // a statement naming a column the schema does not have is a drift the
    // name check cannot see, surfacing only when a consumer runs it
    let conn = applied(sql::MIGRATION_0001);

    // NOTE: the two DDL batches are several statements each, so they are
    // run rather than prepared. Against the freshly applied schema that
    // is the stronger check: it proves they are idempotent, which is
    // why they exist.
    for (name, text) in sql::ALL {
        if *name == "MIGRATION_0001" {
            continue;
        }
        if *name == "ENSURE_INDEXES" {
            conn.execute_batch(text)
                .unwrap_or_else(|err| panic!("`{name}` does not apply: {err:?}"));
            continue;
        }
        assert!(
            conn.prepare(text).is_ok(),
            "`{name}` does not prepare against the inlined schema: {:?}",
            conn.prepare(text).unwrap_err()
        );
    }
}
